kind: pipeline
type: kubernetes
name: build

steps:
- name: docker
  image: plugins/docker
  settings:
    username: sboynton
    password:
      from_secret: registry_password
    registry: 192.168.86.37:5005
    insecure: true
    repo: 192.168.86.37:5005/sboynton/restaurant-picker
    tags: latest

trigger:
  branch:
  - master